apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrakspoc-deployment
  labels:
    app: acrakspoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrakspoc
  template:
    metadata:
      labels:
        app: acrakspoc
    spec:
      containers:
        - name: acrakspoc-container
          image: acrakspoc1.azurecr.io/acrakspoc1/devops-openshift:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8444
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: acrakspoc-service
  labels:
    app: acrakspoc
spec:
  type: LoadBalancer
  selector:
    app: acrakspoc
  ports:
    - port: 8444
      targetPort: 8444
