apiVersion: v1
kind: Service
metadata:
  name: acrakspoc-service
  labels:
    app: acrakspoc
spec:
  type: LoadBalancer
  selector:
    app: acrakspoc
  ports:
    - port: 8444
      targetPort: 8444
